/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface LinearOAuthCallbackRequest {
    /**
     * Authorization code returned by Linear
     */
    code?: string;
    /**
     * State parameter containing encoded authorization data
     */
    state?: string;
    /**
     * Error code returned by Linear, if any
     */
    error?: string;
    /**
     * Detailed error description from Linear, if any
     */
    error_description?: string;
}
