/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GcalendarOAuthCallbackRequest {
    /**
     * Authorization code returned by Google Calendar
     */
    code?: string;
    /**
     * State parameter containing encoded authorization data
     */
    state?: string;
    /**
     * Error code returned by Google Calendar, if any
     */
    error?: string;
    /**
     * Detailed error description from Google Calendar, if any
     */
    error_description?: string;
}
