/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GdocsOAuthCallbackRequest {
    /**
     * Authorization code returned by Google Docs
     */
    code?: string;
    /**
     * State parameter containing encoded authorization data
     */
    state?: string;
    /**
     * Error code returned by Google Docs, if any
     */
    error?: string;
    /**
     * Detailed error description from Google Docs, if any
     */
    error_description?: string;
}
