/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instance_id: "instance_id"
 *     }
 */
export interface RefreshTokenOauthSharesightRefreshTokenPostRequest {
    /**
     * Instance ID for which to refresh the token
     */
    instance_id: string;
}
