/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ConfluenceDataInput {
    /** List of spaces */
    spaces?: Klavis.ConfluenceSpace[];
}
