/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface JiraDataInput {
    /** List of projects with their issues */
    projects?: Klavis.JiraProject[];
    /** List of boards */
    boards?: Klavis.JiraBoard[];
    /** List of sprints */
    sprints?: Klavis.JiraSprint[];
}
