/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface LinearDataInput {
    /** List of projects with their issues. At most 50 projects can be included. */
    projects?: Klavis.LinearProject[];
}
