/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface MondayDataInput {
    /** List of workspaces */
    workspaces?: Klavis.MondayWorkspace[];
    /** List of boards with their groups and items */
    boards?: Klavis.MondayBoard[];
}
