/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface MoneybirdDataInput {
    /** List of ledger accounts to create */
    ledger_accounts?: Klavis.MoneybirdLedgerAccount[];
    /** List of contacts to create */
    contacts?: Klavis.MoneybirdContact[];
    /** List of products to create */
    products?: Klavis.MoneybirdProduct[];
    /** List of projects to create */
    projects?: Klavis.MoneybirdProject[];
    /** List of time entries to create */
    time_entries?: Klavis.MoneybirdTimeEntry[];
    /** List of sales invoices to create */
    sales_invoices?: Klavis.MoneybirdSalesInvoice[];
}
