/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface MotionDataInput {
    /** List of workspaces with their projects and tasks */
    workspaces?: Klavis.MotionWorkspace[];
}
