/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {
 *         root: {
 *             name: "name"
 *         }
 *     }
 */
export interface OneDriveDataInput {
    /** Root folder containing all subfolders and files */
    root: Klavis.OneDriveFolder;
}
