/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ShopifyDataInput {
    /** List of products to create */
    products?: Klavis.ShopifyProduct[];
    /** List of customers to create */
    customers?: Klavis.ShopifyCustomer[];
}
