/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instance_id: "instance_id"
 *     }
 */
export interface RefreshIntercomOauthTokenRequest {
    /**
     * Unique identifier for the MCP connection
     */
    instance_id: string;
}
