/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instance_id: "instance_id",
 *         redirect_url: "redirect_url",
 *         force_refresh: true
 *     }
 */
export interface AuthorizesquareOauthRequest {
    /**
     * Unique identifier for the MCP connection
     */
    instance_id: string;
    /**
     * Optional URL to redirect to after authorization
     */
    redirect_url?: string;
    /**
     * Force re-authorization even if valid tokens exist
     */
    force_refresh?: boolean;
}
