/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Klavis from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace HoneycombOauth {
    export interface Options {
        environment?: core.Supplier<environments.KlavisEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class HoneycombOauth {
    protected readonly _options: HoneycombOauth.Options;

    constructor(_options: HoneycombOauth.Options = {}) {
        this._options = _options;
    }

    /**
     * Start OAuth flow and redirect to authorization page.
     *
     * @param {Klavis.AuthorizehoneycombOauthRequest} request
     * @param {HoneycombOauth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.honeycombOauth.authorizehoneycombOauth({
     *         instance_id: "instance_id",
     *         redirect_url: "redirect_url",
     *         force_refresh: true
     *     })
     */
    public authorizehoneycombOauth(
        request: Klavis.AuthorizehoneycombOauthRequest,
        requestOptions?: HoneycombOauth.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__authorizehoneycombOauth(request, requestOptions));
    }

    private async __authorizehoneycombOauth(
        request: Klavis.AuthorizehoneycombOauthRequest,
        requestOptions?: HoneycombOauth.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { instance_id: instanceId, redirect_url: redirectUrl, force_refresh: forceRefresh } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["instance_id"] = instanceId;
        if (redirectUrl != null) {
            _queryParams["redirect_url"] = redirectUrl;
        }

        if (forceRefresh != null) {
            _queryParams["force_refresh"] = forceRefresh.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                "oauth/honeycomb/authorize",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError("Timeout exceeded when calling GET /oauth/honeycomb/authorize.");
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Refresh OAuth token for an MCP connection.
     *
     * This endpoint triggers a token refresh by making a list_tools request to the MCP server.
     * The MCP SDK will automatically detect if the token is expired and refresh it if a refresh_token is available.
     *
     * @param {Klavis.RefreshHoneycombOauthTokenRequest} request
     * @param {HoneycombOauth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.honeycombOauth.refreshHoneycombOauthToken({
     *         instance_id: "instance_id"
     *     })
     */
    public refreshHoneycombOauthToken(
        request: Klavis.RefreshHoneycombOauthTokenRequest,
        requestOptions?: HoneycombOauth.RequestOptions,
    ): core.HttpResponsePromise<Klavis.McpoAuthSuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__refreshHoneycombOauthToken(request, requestOptions));
    }

    private async __refreshHoneycombOauthToken(
        request: Klavis.RefreshHoneycombOauthTokenRequest,
        requestOptions?: HoneycombOauth.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.McpoAuthSuccessResponse>> {
        const { instance_id: instanceId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["instance_id"] = instanceId;
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                "oauth/honeycomb/refresh_token",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.McpoAuthSuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling POST /oauth/honeycomb/refresh_token.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.apiKey);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
