/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Klavis from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace Sandbox {
    export interface Options {
        environment?: core.Supplier<environments.KlavisEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Sandbox {
    protected readonly _options: Sandbox.Options;

    constructor(_options: Sandbox.Options = {}) {
        this._options = _options;
    }

    /**
     * Acquire an idle sandbox instance for a specific MCP server. The sandbox will be marked as 'occupied'.
     *
     * @param {Klavis.SandboxMcpServer} serverName - The MCP server name
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.createSandbox("jira")
     */
    public createSandbox(
        serverName: Klavis.SandboxMcpServer,
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.CreateSandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSandbox(serverName, requestOptions));
    }

    private async __createSandbox(
        serverName: Klavis.SandboxMcpServer,
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.CreateSandboxResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/${encodeURIComponent(serverName)}`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.CreateSandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError("Timeout exceeded when calling POST /sandbox/{server_name}.");
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve detailed information about a specific sandbox instance.
     *
     * @param {Klavis.SandboxMcpServer} serverName - The MCP server name
     * @param {string} sandboxId - The unique sandbox identifier
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.getSandbox("jira", "sandbox_id")
     */
    public getSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.SandboxInfo> {
        return core.HttpResponsePromise.fromPromise(this.__getSandbox(serverName, sandboxId, requestOptions));
    }

    private async __getSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.SandboxInfo>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/${encodeURIComponent(serverName)}/${encodeURIComponent(sandboxId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.SandboxInfo, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling GET /sandbox/{server_name}/{sandbox_id}.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Release an occupied sandbox back to idle state and marks the sandbox as available for reuse.
     *
     * @param {Klavis.SandboxMcpServer} serverName - The MCP server name
     * @param {string} sandboxId - The unique sandbox identifier
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.deleteSandbox("jira", "sandbox_id")
     */
    public deleteSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.ReleaseSandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSandbox(serverName, sandboxId, requestOptions));
    }

    private async __deleteSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.ReleaseSandboxResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/${encodeURIComponent(serverName)}/${encodeURIComponent(sandboxId)}`,
            ),
            method: "DELETE",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.ReleaseSandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling DELETE /sandbox/{server_name}/{sandbox_id}.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Reset the sandbox to its initial empty state, clearing all data while maintaining the sandbox instance.
     *
     * @param {Klavis.SandboxMcpServer} serverName - The MCP server name
     * @param {string} sandboxId - The unique sandbox identifier
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.resetSandbox("jira", "sandbox_id")
     */
    public resetSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.ResetSandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resetSandbox(serverName, sandboxId, requestOptions));
    }

    private async __resetSandbox(
        serverName: Klavis.SandboxMcpServer,
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.ResetSandboxResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/${encodeURIComponent(serverName)}/${encodeURIComponent(sandboxId)}/reset`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.ResetSandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling POST /sandbox/{server_name}/{sandbox_id}/reset.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Initialize the sandbox with snowflake-specific data following the defined schema.
     *
     * @param {string} sandboxId - The unique sandbox identifier
     * @param {Klavis.SnowflakeData} request
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.initializeSandbox("sandbox_id")
     */
    public initializeSandbox(
        sandboxId: string,
        request: Klavis.SnowflakeData = {},
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.InitializeSandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__initializeSandbox(sandboxId, request, requestOptions));
    }

    private async __initializeSandbox(
        sandboxId: string,
        request: Klavis.SnowflakeData = {},
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.InitializeSandboxResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/snowflake/${encodeURIComponent(sandboxId)}/initialize`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.InitializeSandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling POST /sandbox/snowflake/{sandbox_id}/initialize.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Export all data from the sandbox in the same format used for initialization.
     *
     * @param {string} sandboxId - The unique sandbox identifier
     * @param {Sandbox.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.sandbox.dumpSandbox("sandbox_id")
     */
    public dumpSandbox(
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): core.HttpResponsePromise<Klavis.DumpSandboxResponseSnowflakeData> {
        return core.HttpResponsePromise.fromPromise(this.__dumpSandbox(sandboxId, requestOptions));
    }

    private async __dumpSandbox(
        sandboxId: string,
        requestOptions?: Sandbox.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.DumpSandboxResponseSnowflakeData>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                `sandbox/snowflake/${encodeURIComponent(sandboxId)}/dump`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Klavis.DumpSandboxResponseSnowflakeData,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError(
                    "Timeout exceeded when calling GET /sandbox/snowflake/{sandbox_id}/dump.",
                );
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.apiKey);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
