/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page_size: 1,
 *         page_number: 1
 *     }
 */
export interface GetAllUsersRequest {
    /**
     * Number of results per page (max 1000)
     */
    page_size?: number;
    /**
     * Page number to retrieve (starting from 1)
     */
    page_number?: number;
}
