/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetToolsRequest {
    /**
     * The format to return tools in. Default is MCP Native format for maximum compatibility.
     */
    format?: Klavis.ToolFormat;
}
