/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {
 *         format: "openai",
 *         legacy: true
 *     }
 */
export interface McpServerGetToolsRequest {
    /**
     * The format to return tools in. Default is MCP Native format for maximum compatibility.
     */
    format?: Klavis.ToolFormat;
    /**
     * Whether to use the legacy server. Default is False.
     */
    legacy?: boolean;
}
