/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instanceId: "instanceId",
 *         authToken: "authToken"
 *     }
 */
export interface SetAuthTokenRequest {
    /** The unique identifier for the connection instance */
    instanceId: string;
    /** The authentication token to save */
    authToken: string;
}
