/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Airtable Table object
 */
export interface AirtableTable {
    /** Table name */
    name: string;
    /** Table description */
    description?: string;
    /** Field definitions for this table */
    fields?: Klavis.AirtableField[];
    /** Records in this table */
    records?: Klavis.AirtableRecord[];
}
