/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKeyAuth {
    /** The API key to save (token field) */
    token?: string;
    /** The API key to save (api_key field) */
    api_key?: string;
}
