/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureAdoAuthErrorResponse {
    /** Error message from the OAuth process */
    error: string;
    /** Additional error message */
    message?: string;
}
