/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureAdoAuthSuccessResponse {
    /** Status of the OAuth process */
    status?: string;
    /** Success message */
    message: string;
    /** Additional data related to the response */
    data?: Record<string, unknown>;
}
