/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Schema field for a BigQuery table
 */
export interface BigQueryField {
    /** Field name */
    name: string;
    /** Field type (STRING, INTEGER, FLOAT, BOOLEAN, TIMESTAMP, RECORD, etc.) */
    type: string;
    /** Field mode (NULLABLE, REQUIRED, REPEATED) */
    mode?: string;
    /** Field description */
    description?: string;
    /** Nested fields for RECORD type */
    fields?: Klavis.BigQueryField[];
}
