/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Reference to a BigQuery table
 */
export interface BigQueryTableReference {
    /** Dataset ID */
    datasetId: string;
    /** Table ID */
    tableId: string;
}
