/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Schema for a BigQuery table
 */
export interface BigQueryTableSchema {
    /** List of table fields */
    fields?: Klavis.BigQueryTableFieldSchema[];
}
