/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Schedule data for creating a new schedule via Cal.com API.
 *
 * Attributes:
 *     name: Human-readable schedule name
 *     timeZone: IANA timezone (e.g., "America/New_York")
 *     isDefault: Whether this is the default schedule for the user
 *     availability: List of recurring time slots (optional, defaults to Mon-Fri 9-17)
 *     overrides: List of date-specific availability overrides (optional)
 */
export interface CalcomSchedule {
    /** Human-readable schedule name */
    name: string;
    /** IANA timezone (e.g., 'America/New_York') */
    timeZone: string;
    /** Whether this is the default schedule */
    isDefault?: boolean;
    /** List of recurring time slots */
    availability?: Klavis.TimeSlot[];
    /** List of date-specific availability overrides */
    overrides?: Klavis.Override[];
}
