/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The server's response to a tool call.
 */
export interface CallToolResult {
    /** The content of the tool call */
    content: unknown[];
    /** Whether the tool call was successful */
    isError?: boolean;
}
