/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Marketing campaign
 */
export interface Campaign {
    name: string;
    /** e.g., Email, Webinar, Conference */
    type?: string;
    status?: string;
    /** YYYY-MM-DD */
    start_date?: string;
    /** YYYY-MM-DD */
    end_date?: string;
    expected_revenue?: number;
    budget?: number;
    actual_cost?: number;
    description?: string;
    active?: boolean;
}
