/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * ClickUp List object
 */
export interface ClickUpList {
    /** List name */
    name: string;
    /** List description */
    description?: string;
    /** Tasks in this list */
    tasks?: Klavis.ClickUpTask[];
}
