/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * ClickUp Task object
 */
export interface ClickUpTask {
    /** Task name */
    name: string;
    /** Task description */
    description?: string;
    /** Task priority (1-4) */
    priority?: number;
    /** Comments on this task */
    comments?: Klavis.ClickUpComment[];
}
