/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Compute Engine instance - matches API format
 */
export interface ComputeInstance {
    /** Instance name */
    name: string;
    /** Instance zone */
    zone: string;
    /** Machine type */
    machineType?: string;
    /** Instance status */
    status?: string;
    /** Creation timestamp */
    creationTimestamp?: string;
    /** Instance ID */
    id?: string;
    /** Self link URL */
    selfLink?: string;
    /** Instance description */
    description?: string;
    /** Instance labels */
    labels?: Record<string, string | undefined>;
}
