/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Compute Engine instance
 */
export interface ComputeInstance {
    /** Instance name */
    name: string;
    /** Instance zone */
    zone: string;
    /** Machine type */
    machine_type?: string;
    /** Instance status */
    status?: string;
    /** Instance description */
    description?: string;
    /** Instance labels */
    labels?: Record<string, string | undefined>;
    /** Creation timestamp */
    created_at?: string;
}
