/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Confluence Space object
 */
export interface ConfluenceSpace {
    /** Space identifier */
    identifier: string;
    /** Space name */
    name: string;
    /** Space description */
    description?: string;
    /** Root pages in this space */
    pages?: Klavis.ConfluencePage[];
}
