/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Confluence Comment object
 */
export interface ConfluenceComment {
    /** Comment text content */
    content: string;
}
