/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConnectionType = "SSE" | "StreamableHttp";
export const ConnectionType = {
    Sse: "SSE",
    StreamableHttp: "StreamableHttp",
} as const;
