/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateSelfHostedServerResponse {
    /** The unique identifier for this specific server connection instance. */
    instanceId: string;
    /** The OAuth authorization URL for the specified server, if OAuth is configured. */
    oauthUrl?: string;
}
