/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateServerResponse {
    /** The full URL for connecting to the MCP server, including the instance ID. */
    serverUrl: string;
    /** The unique identifier for this specific server connection integration instance. */
    instanceId: string;
    /** The OAuth URL for authentication if available, supports white label if configured. */
    oauthUrl?: string;
}
