/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Discord Message object
 */
export interface DiscordMessage {
    /** Message text content */
    content: string;
    /** Reactions to this message */
    reactions?: Klavis.DiscordReaction[];
}
