/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Discord Reaction object
 */
export interface DiscordReaction {
    /** Emoji (Unicode like '👍' or custom 'name:id') */
    name: string;
}
