/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Discord Channel - uses existing channel by ID
 */
export interface DiscordChannel {
    /** Discord channel ID (auto-discovered if not provided) */
    channel_id?: string;
    /** Messages in this channel */
    messages?: Klavis.DiscordMessage[];
}
