/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

export interface ExtendedMcpServer {
    id: string;
    name: string;
    description?: string;
    tools?: Klavis.ServerTool[];
    authNeeded?: boolean;
    isAuthenticated?: boolean;
}
