/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExternalServerInfo {
    /** The name of the external server */
    name: string;
    /** The URL of the external MCP server */
    url: string;
}
