/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetInstanceResponse {
    /** The unique identifier of the connection integration instance. */
    instanceId?: string;
    /** Indicates whether authentication is required for this server instance. */
    authNeeded?: boolean;
    /** Indicates whether the instance is authenticated successfully. */
    isAuthenticated?: boolean;
    /** The name of the MCP server associated with the instance. */
    serverName?: string;
    /** The platform associated with the instance. */
    platform?: string;
    /** The user's identifier on the external platform. */
    externalUserId?: string;
    /** The OAuth URL for authentication if available, supports white label if configured. */
    oauthUrl?: string;
}
