/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetOAuthUrlResponse {
    /** The OAuth authorization URL for the specified server. */
    oauthUrl: string;
}
