/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

export interface GetToolsResponse {
    /** List of available tools with their descriptions */
    tools?: Klavis.ServerTool[];
}
