/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetUserAuthResponse {
    success: boolean;
    /** The user identifier */
    userId: string;
    /** The name of the server */
    serverName: string;
    /** The authentication data if available */
    authData?: Record<string, unknown>;
    /** Whether the server has authentication data configured */
    isAuthenticated: boolean;
    message?: string;
}
