/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * GitHub Issue object
 */
export interface GitHubIssue {
    /** Issue ID (read-only, set by GitHub) */
    id?: number;
    /** Issue title */
    issue_title: string;
    /** Issue description/body */
    description?: string;
    /** Issue state: open or closed */
    status?: string;
    /** List of label names */
    labels?: string[];
}
