/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * GitHub Repository object
 */
export interface GitHubRepo {
    /** Repository name */
    name: string;
    /** Repository description */
    description?: string;
    /** List of branches with their folder structures */
    branches?: Klavis.GitHubBranch[];
    /** List of pull requests */
    prs?: Klavis.GitHubPullRequest[];
    /** List of issues */
    issues?: Klavis.GitHubIssue[];
}
