/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * GitHub Pull Request object
 */
export interface GitHubPullRequest {
    /** PR ID (read-only, set by GitHub) */
    id?: number;
    /** Pull request title */
    pr_title: string;
    /** Pull request description/body */
    description?: string;
    /** PR state: open, closed, or merged */
    status?: string;
    /** Head branch name */
    source_branch: string;
    /** Base branch name */
    target_branch?: string;
    /** List of label names */
    labels?: string[];
}
