/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * GitHub Folder object
 */
export interface GitHubFolder {
    /** Folder name */
    name: string;
    /** Folder path within the repository */
    path: string;
    /** Files within this folder */
    files?: Klavis.GitHubFile[];
    /** Subfolders within this folder */
    folders?: Klavis.GitHubFolder[];
}
