/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * GitHub File object
 */
export interface GitHubFile {
    /** File name */
    name: string;
    /** File path within the repository */
    path: string;
    /** File content */
    content?: string;
}
