/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Gmail Draft object with essential fields
 */
export interface GmailDraft {
    /** Draft subject (required) */
    subject: string;
    /** Recipient email address (required) */
    to: string;
    /** CC email addresses (comma-separated) */
    cc?: string;
    /** BCC email addresses (comma-separated) */
    bcc?: string;
    /** Draft body content (required) */
    body: string;
    /** Sender email address (optional, defaults to authenticated user) */
    from?: string;
    /** Reply-to email address */
    reply_to?: string;
}
