/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Complete Google Sheets sandbox data structure
 */
export interface GoogleSheetsDataOutput {
    /** List of Google Sheets spreadsheets */
    spreadsheets?: Klavis.GoogleSheetsSpreadsheet[];
}
