/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Grid data for a sheet
 */
export interface GoogleSheetsGridDataInput {
    /** Starting row index */
    startRow?: number;
    /** Starting column index */
    startColumn?: number;
    /** Row data with values array */
    rowData?: Klavis.GoogleSheetsRowData[];
}
