/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cell value containing only user-entered data
 */
export interface GoogleSheetsCellValue {
    /** The value entered by the user */
    userEnteredValue?: Record<string, unknown>;
}
