/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Google Calendar event object
 */
export interface GoogleCalendarEvent {
    /** Event title/summary (required) */
    summary: string;
    /** Event start time (required) */
    start: Klavis.GoogleCalendarEventDateTime;
    /** Event end time (required) */
    end: Klavis.GoogleCalendarEventDateTime;
    /** Event description */
    description?: string;
    /** Event location */
    location?: string;
    /** List of event attendees */
    attendees?: Klavis.GoogleCalendarAttendee[];
    /** Event color (1-11) */
    colorId?: string;
    /** Visibility (default, public, private, confidential) */
    visibility?: string;
    /** Transparency (opaque, transparent) */
    transparency?: string;
}
