/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Google Docs document object
 */
export interface GoogleDocsDocument {
    /** Document title (required) */
    title: string;
    /** Plain text content of the document */
    content?: string;
}
