/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Event date/time with timezone support
 */
export interface GoogleCalendarEventDateTime {
    /** RFC3339 timestamp (e.g., 2025-12-01T09:00:00-07:00) */
    dateTime?: string;
    /** All-day event date in YYYY-MM-DD format */
    date?: string;
    /** IANA timezone (e.g., America/Los_Angeles) */
    timeZone?: string;
}
