/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * A Google Form with simplified structure
 */
export interface GoogleFormsForm {
    /** The form title visible to responders */
    title: string;
    /** The form description */
    description?: string;
    /** Whether this form is a quiz */
    is_quiz?: boolean;
    /** List of form items (questions and section headers) */
    items?: Klavis.GoogleFormsItem[];
}
