/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Contact object.
 * Can be associated with: Companies.
 */
export interface HubSpotContact {
    /** Contact first name */
    first_name: string;
    /** Contact last name */
    last_name: string;
    /** Contact email address */
    email_address: string;
    /** Contact phone number */
    phone_number?: string;
    /** Contact job title */
    job_title?: string;
}
