/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Contact object.
 * Can be associated with: Companies.
 */
export interface HubSpotContact {
    /** Contact first name */
    firstname: string;
    /** Contact last name */
    lastname: string;
    /** Contact email address */
    email: string;
    /** Contact phone number */
    phone?: string;
    /** Contact job title */
    job_title?: string;
}
