/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Ticket object.
 * Can be associated with: Contacts, Companies.
 */
export interface HubSpotTicket {
    /** Ticket subject */
    subject: string;
    /** Ticket content/description */
    content?: string;
    /** Ticket pipeline */
    pipeline?: string;
    /** Ticket pipeline stage */
    pipeline_stage?: string;
    /** Ticket priority (HIGH, MEDIUM, LOW) */
    priority?: string;
}
