/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Deal object.
 * Can be associated with: Contacts, Companies.
 */
export interface HubSpotDeal {
    /** Deal name */
    deal_name: string;
    /** Deal amount */
    amount?: string;
    /** Deal stage */
    deal_stage?: string;
    /** Deal pipeline */
    pipeline?: string;
    /** Expected close date */
    close_date?: string;
}
