/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Company object.
 * Base object, typically doesn't associate upwards in this schema, but contacts/deals associate to it.
 */
export interface HubSpotCompany {
    /** Company name */
    company_name: string;
    /** Company website domain */
    website_domain?: string;
    /** Company industry */
    industry?: string;
    /** Company city */
    city?: string;
    /** Company state/region */
    state_region?: string;
    /** Company country */
    country?: string;
    /** Company phone number */
    phone_number?: string;
    /** Number of employees */
    employee_count?: string;
    /** Yearly revenue */
    yearly_revenue?: string;
}
