/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Company object.
 * Base object, typically doesn't associate upwards in this schema, but contacts/deals associate to it.
 */
export interface HubSpotCompany {
    /** Company name */
    name: string;
    /** Company domain/website */
    domain?: string;
    /** Company industry */
    industry?: string;
    /** Company city */
    city?: string;
    /** Company state/region */
    state?: string;
    /** Company country */
    country?: string;
    /** Company phone number */
    phone?: string;
    /** Number of employees */
    number_of_employees?: string;
    /** Annual revenue */
    annual_revenue?: string;
}
