/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HubSpot Task object.
 * Can be associated with: Contacts, Companies, Deals, Tickets.
 */
export interface HubSpotTask {
    /** Task subject/title */
    subject: string;
    /** Task body/description */
    body?: string;
    /** Task status (NOT_STARTED, IN_PROGRESS, COMPLETED, WAITING, DEFERRED) */
    status?: string;
    /** Task priority (HIGH, MEDIUM, LOW) */
    priority?: string;
    /** Task due date (ISO 8601 format) */
    due_date?: string;
}
