/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Response model for sandbox initialization
 */
export interface InitializeSandboxResponse {
    /** Sandbox identifier */
    sandbox_id: string;
    /** Current status */
    status: Klavis.SandboxStatus;
    /** Initialization result message */
    message: string;
    /** Count of records created per object type */
    records_created?: Record<string, number | undefined>;
}
