/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Lifecycle rule for a storage bucket
 */
export interface LifecycleRule {
    /** Action type (Delete, SetStorageClass) */
    action: string;
    /** Target storage class for SetStorageClass action */
    action_storage_class?: string;
    /** Age in days to trigger rule */
    age_days?: number;
    /** Created before date */
    created_before?: string;
    /** Apply to live versions only */
    is_live?: boolean;
    /** Number of newer versions to keep */
    num_newer_versions?: number;
}
