/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Linear Project object
 */
export interface LinearProject {
    /** Project name */
    name: string;
    /** Project description */
    description?: string;
    /** Project state (planned, started, paused, completed, canceled) */
    state?: string;
    /** Issues in this project */
    issues?: Klavis.LinearIssue[];
}
