/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Complete Linear sandbox data structure.
 *
 * Relational structure for initialization:
 * - Projects contain Issues
 * - Issues contain Comments
 */
export interface LinearData {
    /** List of projects with their issues. At most 50 projects can be included. */
    projects?: Klavis.LinearProject[];
}
