/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cloud Logging bucket
 */
export interface LogBucket {
    /** Bucket name/ID */
    name: string;
    /** Bucket location */
    location?: string;
    /** Retention period in days */
    retention_days?: number;
    /** Bucket description */
    description?: string;
    /** Creation timestamp */
    created_at?: string;
    /** Update timestamp */
    updated_at?: string;
}
