/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cloud Logging log entry
 */
export interface LogEntry {
    /** Log name */
    log_name: string;
    /** Text message payload */
    message?: string;
    /** JSON payload */
    json_data?: Record<string, unknown>;
    /** Log severity (DEBUG, INFO, WARNING, ERROR, CRITICAL) */
    severity?: string;
    /** Entry timestamp */
    timestamp?: string;
    /** Resource type (e.g., gce_instance, cloud_function) */
    resource_type?: string;
    /** Resource labels */
    resource_labels?: Record<string, string | undefined>;
}
