/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cloud Logging sink
 */
export interface LogSink {
    /** Sink name */
    name: string;
    /** Log filter expression */
    filter?: string;
    /** Sink description */
    description?: string;
    /** Creation timestamp */
    created_at?: string;
    /** Update timestamp */
    updated_at?: string;
}
