/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type McpServerName =
    | "Affinity"
    | "Airtable"
    | "Asana"
    | "Attio"
    | "Brave Search"
    | "ClickUp"
    | "Close"
    | "Confluence"
    | "Discord"
    | "Doc2markdown"
    | "Firecrawl Deep Research"
    | "Firecrawl Web Search"
    | "GitHub"
    | "Gmail"
    | "Gong"
    | "Google Calendar"
    | "Google Docs"
    | "Google Drive"
    | "Google Sheets"
    | "HubSpot"
    | "Jira"
    | "Klavis ReportGen"
    | "Linear"
    | "LinkedIn"
    | "Markdown2doc"
    | "Motion"
    | "Notion"
    | "Plai"
    | "Postgres"
    | "QuickBooks"
    | "Resend"
    | "Salesforce"
    | "Slack"
    | "Supabase"
    | "WhatsApp"
    | "WordPress"
    | "YouTube";
export const McpServerName = {
    Affinity: "Affinity",
    Airtable: "Airtable",
    Asana: "Asana",
    Attio: "Attio",
    BraveSearch: "Brave Search",
    ClickUp: "ClickUp",
    Close: "Close",
    Confluence: "Confluence",
    Discord: "Discord",
    Doc2Markdown: "Doc2markdown",
    FirecrawlDeepResearch: "Firecrawl Deep Research",
    FirecrawlWebSearch: "Firecrawl Web Search",
    Github: "GitHub",
    Gmail: "Gmail",
    Gong: "Gong",
    GoogleCalendar: "Google Calendar",
    GoogleDocs: "Google Docs",
    GoogleDrive: "Google Drive",
    GoogleSheets: "Google Sheets",
    HubSpot: "HubSpot",
    Jira: "Jira",
    KlavisReportGen: "Klavis ReportGen",
    Linear: "Linear",
    LinkedIn: "LinkedIn",
    Markdown2Doc: "Markdown2doc",
    Motion: "Motion",
    Notion: "Notion",
    Plai: "Plai",
    Postgres: "Postgres",
    QuickBooks: "QuickBooks",
    Resend: "Resend",
    Salesforce: "Salesforce",
    Slack: "Slack",
    Supabase: "Supabase",
    WhatsApp: "WhatsApp",
    WordPress: "WordPress",
    Youtube: "YouTube",
} as const;
