/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type McpServerName =
    | "Affinity"
    | "Airtable"
    | "Asana"
    | "Attio"
    | "Brave Search"
    | "Cal.com"
    | "ClickUp"
    | "Close"
    | "Coinbase"
    | "Confluence"
    | "Discord"
    | "Dropbox"
    | "Doc2markdown"
    | "Exa"
    | "Firecrawl Deep Research"
    | "Firecrawl Web Search"
    | "Freshdesk"
    | "GitHub"
    | "GitLab"
    | "Gmail"
    | "Gong"
    | "Google Calendar"
    | "Google Docs"
    | "Google Drive"
    | "Google Jobs"
    | "Google Sheets"
    | "Hacker News"
    | "Heygen"
    | "HubSpot"
    | "Jira"
    | "Klavis ReportGen"
    | "Linear"
    | "LinkedIn"
    | "Markdown2doc"
    | "Mem0"
    | "Mixpanel"
    | "Monday"
    | "Moneybird"
    | "Motion"
    | "Notion"
    | "Onedrive"
    | "Openrouter"
    | "Plai"
    | "Postgres"
    | "QuickBooks"
    | "Resend"
    | "Salesforce"
    | "Shopify"
    | "Slack"
    | "Supabase"
    | "Tavily"
    | "Vercel"
    | "WhatsApp"
    | "WordPress"
    | "YouTube";
export const McpServerName = {
    Affinity: "Affinity",
    Airtable: "Airtable",
    Asana: "Asana",
    Attio: "Attio",
    BraveSearch: "Brave Search",
    CalCom: "Cal.com",
    ClickUp: "ClickUp",
    Close: "Close",
    Coinbase: "Coinbase",
    Confluence: "Confluence",
    Discord: "Discord",
    Dropbox: "Dropbox",
    Doc2Markdown: "Doc2markdown",
    Exa: "Exa",
    FirecrawlDeepResearch: "Firecrawl Deep Research",
    FirecrawlWebSearch: "Firecrawl Web Search",
    Freshdesk: "Freshdesk",
    Github: "GitHub",
    GitLab: "GitLab",
    Gmail: "Gmail",
    Gong: "Gong",
    GoogleCalendar: "Google Calendar",
    GoogleDocs: "Google Docs",
    GoogleDrive: "Google Drive",
    GoogleJobs: "Google Jobs",
    GoogleSheets: "Google Sheets",
    HackerNews: "Hacker News",
    Heygen: "Heygen",
    HubSpot: "HubSpot",
    Jira: "Jira",
    KlavisReportGen: "Klavis ReportGen",
    Linear: "Linear",
    LinkedIn: "LinkedIn",
    Markdown2Doc: "Markdown2doc",
    Mem0: "Mem0",
    Mixpanel: "Mixpanel",
    Monday: "Monday",
    Moneybird: "Moneybird",
    Motion: "Motion",
    Notion: "Notion",
    Onedrive: "Onedrive",
    Openrouter: "Openrouter",
    Plai: "Plai",
    Postgres: "Postgres",
    QuickBooks: "QuickBooks",
    Resend: "Resend",
    Salesforce: "Salesforce",
    Shopify: "Shopify",
    Slack: "Slack",
    Supabase: "Supabase",
    Tavily: "Tavily",
    Vercel: "Vercel",
    WhatsApp: "WhatsApp",
    WordPress: "WordPress",
    Youtube: "YouTube",
} as const;
