/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type McpServerName =
    | "Affinity"
    | "Airtable"
    | "Amplitude"
    | "Asana"
    | "Attio"
    | "Box"
    | "Brave Search"
    | "Cal.com"
    | "Canva"
    | "ClickUp"
    | "Close"
    | "Cloudflare"
    | "Coinbase"
    | "Confluence"
    | "Dialpad"
    | "Discord"
    | "Doc2markdown"
    | "DocuSign"
    | "Dropbox"
    | "ElevenLabs"
    | "Exa"
    | "Fathom"
    | "Fetch URL"
    | "Figma"
    | "Fireflies"
    | "Firecrawl Deep Research"
    | "Firecrawl Web Search"
    | "Freshdesk"
    | "GitHub"
    | "GitLab"
    | "Gmail"
    | "Gong"
    | "Google Calendar"
    | "Google Docs"
    | "Google Drive"
    | "Google Jobs"
    | "Google Sheets"
    | "Google Forms"
    | "Google Cloud"
    | "Hacker News"
    | "Heygen"
    | "HubSpot"
    | "Intercom"
    | "Jira"
    | "Klaviyo"
    | "Klavis ReportGen"
    | "Linear"
    | "LinkedIn"
    | "Markdown2doc"
    | "Mem0"
    | "Microsoft Teams"
    | "Mixpanel"
    | "Monday"
    | "Moneybird"
    | "Motion"
    | "Notion"
    | "OneDrive"
    | "Openrouter"
    | "Outlook Mail"
    | "Outlook Calendar"
    | "PagerDuty"
    | "Pipedrive"
    | "Plai"
    | "Postgres"
    | "PostHog"
    | "Postman"
    | "QuickBooks"
    | "Resend"
    | "Salesforce"
    | "SendGrid"
    | "Shopify"
    | "Slack"
    | "Snowflake"
    | "Stripe"
    | "Supabase"
    | "Tavily"
    | "Vercel"
    | "WhatsApp"
    | "WordPress"
    | "YouTube"
    | "Zendesk"
    | "ServiceNow"
    | "PayPal"
    | "Sentry"
    | "Netlify"
    | "Hugging Face"
    | "Square"
    | "Clockwise"
    | "Jotform"
    | "Honeycomb"
    | "Zoho Mail"
    | "Sharesight"
    | "Weights and Biases"
    | "Instagram";
export const McpServerName = {
    Affinity: "Affinity",
    Airtable: "Airtable",
    Amplitude: "Amplitude",
    Asana: "Asana",
    Attio: "Attio",
    Box: "Box",
    BraveSearch: "Brave Search",
    CalCom: "Cal.com",
    Canva: "Canva",
    Clickup: "ClickUp",
    Close: "Close",
    Cloudflare: "Cloudflare",
    Coinbase: "Coinbase",
    Confluence: "Confluence",
    Dialpad: "Dialpad",
    Discord: "Discord",
    Doc2Markdown: "Doc2markdown",
    Docusign: "DocuSign",
    Dropbox: "Dropbox",
    ElevenLabs: "ElevenLabs",
    Exa: "Exa",
    Fathom: "Fathom",
    FetchUrl: "Fetch URL",
    Figma: "Figma",
    Fireflies: "Fireflies",
    FirecrawlDeepResearch: "Firecrawl Deep Research",
    FirecrawlWebSearch: "Firecrawl Web Search",
    Freshdesk: "Freshdesk",
    Github: "GitHub",
    Gitlab: "GitLab",
    Gmail: "Gmail",
    Gong: "Gong",
    GoogleCalendar: "Google Calendar",
    GoogleDocs: "Google Docs",
    GoogleDrive: "Google Drive",
    GoogleJobs: "Google Jobs",
    GoogleSheets: "Google Sheets",
    GoogleForms: "Google Forms",
    GoogleCloud: "Google Cloud",
    HackerNews: "Hacker News",
    Heygen: "Heygen",
    Hubspot: "HubSpot",
    Intercom: "Intercom",
    Jira: "Jira",
    Klaviyo: "Klaviyo",
    KlavisReportGen: "Klavis ReportGen",
    Linear: "Linear",
    Linkedin: "LinkedIn",
    Markdown2Doc: "Markdown2doc",
    Mem0: "Mem0",
    MicrosoftTeams: "Microsoft Teams",
    Mixpanel: "Mixpanel",
    Monday: "Monday",
    Moneybird: "Moneybird",
    Motion: "Motion",
    Notion: "Notion",
    Onedrive: "OneDrive",
    Openrouter: "Openrouter",
    OutlookMail: "Outlook Mail",
    OutlookCalendar: "Outlook Calendar",
    Pagerduty: "PagerDuty",
    Pipedrive: "Pipedrive",
    Plai: "Plai",
    Postgres: "Postgres",
    Posthog: "PostHog",
    Postman: "Postman",
    Quickbooks: "QuickBooks",
    Resend: "Resend",
    Salesforce: "Salesforce",
    Sendgrid: "SendGrid",
    Shopify: "Shopify",
    Slack: "Slack",
    Snowflake: "Snowflake",
    Stripe: "Stripe",
    Supabase: "Supabase",
    Tavily: "Tavily",
    Vercel: "Vercel",
    Whatsapp: "WhatsApp",
    Wordpress: "WordPress",
    Youtube: "YouTube",
    Zendesk: "Zendesk",
    ServiceNow: "ServiceNow",
    PayPal: "PayPal",
    Sentry: "Sentry",
    Netlify: "Netlify",
    HuggingFace: "Hugging Face",
    Square: "Square",
    Clockwise: "Clockwise",
    Jotform: "Jotform",
    Honeycomb: "Honeycomb",
    ZohoMail: "Zoho Mail",
    Sharesight: "Sharesight",
    WeightsAndBiases: "Weights and Biases",
    Instagram: "Instagram",
} as const;
