/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Mem0 Memory object
 */
export interface Mem0Memory {
    /** Memory ID (read-only, set by Mem0) */
    id?: string;
    /** Memory content (returned from API) */
    content_text?: string;
    /** Array of message objects representing the content */
    message_list?: Klavis.Mem0Message[];
    /** Agent ID */
    agent_id?: string;
    /** User ID */
    user_id?: string;
    /** App ID */
    app_id?: string;
    /** Run ID */
    run_id?: string;
    /** Additional metadata */
    metadata?: Record<string, unknown>;
    /** String to include specific preferences in the memory */
    include_preferences?: string;
    /** String to exclude specific preferences in the memory */
    exclude_preferences?: string;
    /** Whether to infer memories or directly store messages */
    auto_infer?: boolean;
    /** Response format structure (v1.0 or v1.1) */
    response_format?: string;
    /** List of custom categories with name and description */
    category_definitions?: Record<string, string>[];
    /** Project-specific guidelines for handling memories */
    processing_instructions?: string;
    /** Whether the memory is immutable */
    read_only?: boolean;
    /** Whether to add memory asynchronously */
    background_processing?: boolean;
    /** Unix timestamp of the memory */
    timestamp?: number;
    /** Creation timestamp */
    created_at?: string;
    /** Last update timestamp */
    updated_at?: string;
}
