/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Message object for memory
 */
export interface Mem0Message {
    /** Role of the message sender (user or assistant) */
    role: string;
    /** Content of the message */
    content: string;
}
