/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Monday.com Update (Comment) object - DELETE SUPPORTED
 */
export interface MondayUpdate {
    /** Update text content */
    body: string;
}
