/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Monday.com Item (Task/Row) object - DELETE SUPPORTED
 */
export interface MondayItem {
    /** Item name */
    name: string;
    /** Column values as JSON object */
    column_values?: Record<string, unknown>;
    /** Updates/comments on this item */
    updates?: Klavis.MondayUpdate[];
    /** Subitems (nested items) */
    subitems?: Klavis.MondaySubitem[];
}
