/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Monday.com Board object - DELETE SUPPORTED
 */
export interface MondayBoard {
    /** Board name */
    name: string;
    /** Board description */
    description?: string;
    /** Board kind (public, private, share) */
    board_kind?: string;
    /** Workspace ID this board belongs to (for initialization) */
    workspace_id?: string;
    /** Groups in this board */
    groups?: Klavis.MondayGroup[];
}
