/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Moneybird time entry - API format
 *
 * Note: During initialization, this will be linked to a project and contact automatically.
 * The started_at and ended_at timestamps will be generated based on the hours field.
 *
 * Attributes:
 *     description: Description of work performed
 *     hours: Number of hours worked
 *     billable: Whether this time is billable
 */
export interface MoneybirdTimeEntry {
    /** Description of work performed */
    description: string;
    /** Number of hours worked */
    hours: number;
    /** Whether this time is billable */
    billable?: boolean;
}
