/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Invoice line item details
 */
export interface MoneybirdInvoiceDetail {
    /** Line item description */
    description: string;
    /** Unit price as string */
    price: string;
    /** Quantity as string */
    amount: string;
}
