/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Complete Moneybird sandbox data structure - API format
 *
 * Note: Objects are created in dependency order:
 * 1. Ledger accounts (no dependencies)
 * 2. Contacts (no dependencies)
 * 3. Products (no dependencies, but needs tax rates from system)
 * 4. Projects (no dependencies)
 * 5. Time entries (linked to projects and contacts)
 * 6. Sales invoices (linked to contacts)
 */
export interface MoneybirdData {
    /** List of ledger accounts to create */
    ledger_accounts?: Klavis.MoneybirdLedgerAccount[];
    /** List of contacts to create */
    contacts?: Klavis.MoneybirdContact[];
    /** List of products to create */
    products?: Klavis.MoneybirdProduct[];
    /** List of projects to create */
    projects?: Klavis.MoneybirdProject[];
    /** List of time entries to create */
    time_entries?: Klavis.MoneybirdTimeEntry[];
    /** List of sales invoices to create */
    sales_invoices?: Klavis.MoneybirdSalesInvoice[];
}
