/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Motion Project object - supports DELETE operation
 */
export interface MotionProject {
    /** Project name */
    name: string;
    /** Project description */
    description?: string;
    /** Project due date in ISO 8601 format */
    due_date?: string;
    /** Project priority: ASAP, HIGH, MEDIUM, or LOW */
    priority?: string;
    /** Project labels */
    labels?: string[];
    /** Tasks in this project */
    tasks?: Klavis.MotionTask[];
}
