/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Motion Task object - supports DELETE operation
 */
export interface MotionTask {
    /** Task name/title */
    name: string;
    /** Task description (supports Markdown) */
    description?: string;
    /** Task status (e.g., 'TODO', 'IN_PROGRESS', 'COMPLETED') */
    status?: string;
    /** Task priority: ASAP, HIGH, MEDIUM, or LOW */
    priority?: string;
    /** Due date in ISO 8601 format */
    due_date?: string;
    /** Estimated duration in minutes */
    duration?: number;
    /** Task labels for categorization */
    labels?: string[];
    /** Comments on this task */
    comments?: Klavis.MotionComment[];
}
