/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

export interface MultiServerToolsResponse {
    /** Whether tools were retrieved successfully for all requested servers. */
    success: boolean;
    /** The format of the returned tools for all servers. */
    format: Klavis.ToolFormat;
    /** Per-server results including any partial failures. */
    results?: Klavis.ServerToolsResult[];
    /** Aggregated error message when one or more servers fail. */
    error?: string;
}
