/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OAuthServerName =
    | "Slack"
    | "Supabase"
    | "Notion"
    | "GitHub"
    | "Jira"
    | "Confluence"
    | "WordPress"
    | "Gmail"
    | "Google Drive"
    | "Google Calendar"
    | "Google Sheets"
    | "Google Docs"
    | "Attio"
    | "Salesforce"
    | "Linear"
    | "Asana"
    | "Close"
    | "ClickUp";
export const OAuthServerName = {
    Slack: "Slack",
    Supabase: "Supabase",
    Notion: "Notion",
    GitHub: "GitHub",
    Jira: "Jira",
    Confluence: "Confluence",
    WordPress: "WordPress",
    Gmail: "Gmail",
    GoogleDrive: "Google Drive",
    GoogleCalendar: "Google Calendar",
    GoogleSheets: "Google Sheets",
    GoogleDocs: "Google Docs",
    Attio: "Attio",
    Salesforce: "Salesforce",
    Linear: "Linear",
    Asana: "Asana",
    Close: "Close",
    ClickUp: "ClickUp",
} as const;
