/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OAuthServerName =
    | "Airtable"
    | "Asana"
    | "Attio"
    | "Canva"
    | "ClickUp"
    | "Close"
    | "Confluence"
    | "GitHub"
    | "Gmail"
    | "Google Calendar"
    | "Google Docs"
    | "Google Drive"
    | "Google Sheets"
    | "HubSpot"
    | "Jira"
    | "Linear"
    | "LinkedIn"
    | "Monday"
    | "Moneybird"
    | "Notion"
    | "Onedrive"
    | "Salesforce"
    | "Shopify"
    | "Slack"
    | "Supabase"
    | "Xero"
    | "WordPress"
    | "Dropbox"
    | "QuickBooks";
export const OAuthServerName = {
    Airtable: "Airtable",
    Asana: "Asana",
    Attio: "Attio",
    Canva: "Canva",
    ClickUp: "ClickUp",
    Close: "Close",
    Confluence: "Confluence",
    GitHub: "GitHub",
    Gmail: "Gmail",
    GoogleCalendar: "Google Calendar",
    GoogleDocs: "Google Docs",
    GoogleDrive: "Google Drive",
    GoogleSheets: "Google Sheets",
    HubSpot: "HubSpot",
    Jira: "Jira",
    Linear: "Linear",
    LinkedIn: "LinkedIn",
    Monday: "Monday",
    Moneybird: "Moneybird",
    Notion: "Notion",
    Onedrive: "Onedrive",
    Salesforce: "Salesforce",
    Shopify: "Shopify",
    Slack: "Slack",
    Supabase: "Supabase",
    Xero: "Xero",
    WordPress: "WordPress",
    Dropbox: "Dropbox",
    QuickBooks: "QuickBooks",
} as const;
