/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * OneDrive Folder object
 */
export interface OneDriveFolder {
    /** Folder ID (read-only, set by OneDrive) */
    id?: string;
    /** Folder name */
    name: string;
    /** List of subfolders */
    folders?: Klavis.OneDriveFolder[];
    /** List of files in the folder */
    files?: Klavis.OneDriveFile[];
}
