/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OneDrive File object
 */
export interface OneDriveFile {
    /** File ID (read-only, set by OneDrive) */
    id?: string;
    /** File name */
    name: string;
    /** File content (text files only) */
    content?: string;
}
