/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a date-specific override to the regular schedule.
 *
 * Attributes:
 *     date: Date in YYYY-MM-DD format
 *     startTime: Start time in HH:MM format (24-hour)
 *     endTime: End time in HH:MM format (24-hour)
 */
export interface Override {
    date: string;
    startTime: string;
    endTime: string;
}
