/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Response model for sandbox reset
 */
export interface ResetSandboxResponse {
    /** Sandbox identifier */
    sandbox_id: string;
    /** Current status after reset */
    status: Klavis.SandboxStatus;
    /** Reset result message */
    message: string;
}
