/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Resend Email object - standalone transactional email
 */
export interface ResendEmail {
    /** Email ID (read-only, set by Resend) */
    id?: string;
    /** Sender email address */
    from: string;
    /** Recipient email addresses */
    to: string[];
    /** Email subject */
    subject: string;
    /** HTML content of the email */
    html?: string;
    /** Plain text content of the email */
    text?: string;
    /** Reply-to email address */
    reply_to?: string;
    /** CC email addresses */
    cc?: string[];
    /** BCC email addresses */
    bcc?: string[];
    /** Email tags for categorization */
    tags?: Record<string, string>[];
    /** Creation timestamp */
    created_at?: string;
}
