/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Salesforce Case object with comprehensive field support
 */
export interface SalesforceCase {
    /** Case subject (required) */
    Subject: string;
    /** Case status (e.g., New, Working, Closed) */
    Status?: string;
    /** Priority (e.g., High, Medium, Low) */
    Priority?: string;
    /** Case origin (e.g., Phone, Email, Web) */
    Origin?: string;
    /** Case type (e.g., Problem, Question, Feature Request) */
    Type?: string;
    /** Case reason */
    Reason?: string;
    /** Related account ID (18-char Salesforce ID) */
    AccountId?: string;
    /** Related contact ID (18-char Salesforce ID) */
    ContactId?: string;
    /** Case description */
    Description?: string;
    /** Supplied email address */
    SuppliedEmail?: string;
    /** Supplied name */
    SuppliedName?: string;
    /** Supplied phone number */
    SuppliedPhone?: string;
}
