/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Salesforce Contact object with comprehensive field support
 */
export interface SalesforceContact {
    /** First name */
    FirstName?: string;
    /** Last name (required) */
    LastName: string;
    /** Email address */
    Email?: string;
    /** Phone number */
    Phone?: string;
    /** Mobile phone number */
    MobilePhone?: string;
    /** Job title */
    Title?: string;
    /** Department */
    Department?: string;
    /** Related account ID (18-char Salesforce ID) */
    AccountId?: string;
    /** Mailing street address */
    MailingStreet?: string;
    /** Mailing city */
    MailingCity?: string;
    /** Mailing state/province */
    MailingState?: string;
    /** Mailing postal code */
    MailingPostalCode?: string;
    /** Mailing country */
    MailingCountry?: string;
    /** Contact description */
    Description?: string;
    /** Lead source (e.g., Web, Phone Inquiry, Partner Referral) */
    LeadSource?: string;
}
