/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Salesforce Account object with comprehensive field support
 */
export interface SalesforceAccount {
    /** Account name (required) */
    Name: string;
    /** Industry (e.g., Technology, Healthcare, Finance) */
    Industry?: string;
    /** Account type (e.g., Customer, Prospect, Partner) */
    Type?: string;
    /** Phone number */
    Phone?: string;
    /** Website URL */
    Website?: string;
    /** Annual revenue */
    AnnualRevenue?: number;
    /** Number of employees */
    NumberOfEmployees?: number;
    /** Billing street address */
    BillingStreet?: string;
    /** Billing city */
    BillingCity?: string;
    /** Billing state/province */
    BillingState?: string;
    /** Billing postal code */
    BillingPostalCode?: string;
    /** Billing country */
    BillingCountry?: string;
    /** Account description */
    Description?: string;
    /** Account rating (e.g., Hot, Warm, Cold) */
    Rating?: string;
}
