/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ServerToolsResult {
    /** The name of the MCP server. */
    serverName: string;
    /** Whether the tools were retrieved successfully for this server. */
    success: boolean;
    /** Tools available for the server when the request succeeds. */
    tools?: unknown[];
    /** The error message if the request failed for this server. */
    error?: string;
}
