/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Customer address information
 *
 * Attributes:
 *     address1: Street address line 1 (optional - may not be present in API response)
 *     city: City name (optional - may not be present in API response)
 *     province: State/province code (optional - may not be present in API response)
 *     zip: Postal/ZIP code (optional - may not be present in API response)
 *     country: Country code (e.g., 'US') (optional - may not be present in API response)
 */
export interface ShopifyAddress {
    /** Street address line 1 */
    address1?: string;
    /** City name */
    city?: string;
    /** State/province code */
    province?: string;
    /** Postal/ZIP code */
    zip?: string;
    /** Country code (e.g., 'US') */
    country?: string;
}
