/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Snowflake Database object
 */
export interface SnowflakeDatabase {
    /** Database name, cannot be 'SNOWFLAKE' or 'USER$...' since they are default databases */
    name: string;
    /** Database description */
    description?: string;
    /** Schemas in this database */
    schemas?: Klavis.SnowflakeSchema[];
}
