/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Snowflake Table Column definition
 */
export interface SnowflakeColumn {
    /** Column name */
    name: string;
    /** Column data type (e.g., VARCHAR, NUMBER, TIMESTAMP) */
    data_type: string;
    /** Whether the column can be NULL */
    nullable?: boolean;
    /** Default value for the column */
    default?: string;
}
