/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Action for a lifecycle rule
 */
export interface StorageBucketLifecycleRuleAction {
    /** Action type (Delete, SetStorageClass) */
    type: string;
    /** Storage class for SetStorageClass action */
    storageClass?: string;
}
