/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Cloud Storage bucket object - matches API format
 */
export interface StorageBucket {
    /** Bucket name */
    name: string;
    /** Bucket location */
    location?: string;
    /** Storage class */
    storageClass?: string;
    /** Versioning configuration */
    versioning?: Klavis.StorageBucketVersioning;
    /** Lifecycle configuration */
    lifecycle?: Klavis.StorageBucketLifecycle;
    /** Creation timestamp */
    timeCreated?: string;
    /** Last update timestamp */
    updated?: string;
}
