/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * A lifecycle rule for a bucket
 */
export interface StorageBucketLifecycleRule {
    /** Rule action */
    action: Klavis.StorageBucketLifecycleRuleAction;
    /** Rule condition */
    condition: Klavis.StorageBucketLifecycleRuleCondition;
}
