/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StrataDeleteServersResponse {
    /** List of Klavis MCP server names that were deleted */
    deletedServers: string[];
    /** List of external MCP server names that were deleted */
    deletedExternalServers: string[];
}
