/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

export interface StrataAddServersResponse {
    /** List of Klavis integration that were added */
    addedServers: string[];
    /** List of external MCP servers that were added with name and URL */
    addedExternalServers?: Klavis.ExternalServerInfo[];
    /** Map of connected integration to OAuth URL, supports white labeling if configured */
    oauthUrls?: Record<string, string>;
    /** Map of connected integration to API key setup URL */
    apiKeyUrls?: Record<string, string>;
}
