/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Complete Supabase sandbox data structure
 */
export interface SupabaseDataOutput {
    /** List of Supabase projects */
    projects?: Klavis.SupabaseProject[];
}
