/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supabase Table object
 */
export interface SupabaseTable {
    /** Table name */
    name: string;
    /** Table schema mapping column names to types */
    columns: Record<string, string>;
    /** Table data rows */
    rows?: Record<string, unknown>[];
}
