/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Supabase Project object
 */
export interface SupabaseProject {
    /** Project ID (read-only, set by Supabase) */
    id?: string;
    /** Project name */
    name: string;
    /** List of tables in the project */
    tables?: Klavis.SupabaseTable[];
}
