/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Teams Chat Member object
 */
export interface TeamsChatMember {
    /** Member ID (read-only, set by Teams) */
    member_id?: string;
    /** Member display name */
    member_name?: string;
    /** User email for creating chats */
    member_email?: string;
}
