/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Teams Message object
 */
export interface TeamsMessage {
    /** Message ID (read-only, set by Teams) */
    id?: string;
    /** Message content */
    body: string;
}
