/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../index.js";

/**
 * Teams Channel object
 */
export interface TeamsChannel {
    /** Channel ID (read-only, set by Teams) */
    channel_id?: string;
    /** Channel display name */
    name: string;
    /** Channel description */
    channel_description?: string;
    /** List of messages in the channel */
    channel_messages?: Klavis.TeamsMessage[];
}
