/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Teams Chat Member object
 */
export interface TeamsChatMember {
    /** Member ID (read-only, set by Teams) */
    id?: string;
    /** Member display name */
    displayName?: string;
    /** User email for creating chats */
    email?: string;
}
