/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a recurring time slot in a schedule.
 *
 * Attributes:
 *     days: List of weekday names (Monday, Tuesday, etc.)
 *     startTime: Start time in HH:MM format (24-hour)
 *     endTime: End time in HH:MM format (24-hour)
 */
export interface TimeSlot {
    days: string[];
    startTime: string;
    endTime: string;
}
