/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToolFormat = "openai" | "anthropic" | "gemini" | "mcp_native";
export const ToolFormat = {
    Openai: "openai",
    Anthropic: "anthropic",
    Gemini: "gemini",
    McpNative: "mcp_native",
} as const;
