/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateServerInstanceResponse {
    /** The unique identifier of the updated connection integration instance. */
    instanceId: string;
    /** The current read-only status of the connection. */
    isReadOnly: boolean;
    /** A message indicating the result of the update operation. */
    message: string;
}
