/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WhiteLabelingResponse {
    /** Whether the operation was successful */
    success: boolean;
    /** The white labeling data if successful */
    data?: Record<string, unknown>;
    /** Error message if unsuccessful */
    message?: string;
}
