/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CanvaOAuthCallbackRequest {
    /**
     * Authorization code from Canva
     */
    code?: string;
    /**
     * State parameter to prevent CSRF
     */
    state?: string;
    /**
     * Error code if authorization failed
     */
    error?: string;
    /**
     * Error description if authorization failed
     */
    error_description?: string;
}
