/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../../index.js";

/**
 * @example
 *     {
 *         client_id: "client_id",
 *         client_secret: "client_secret",
 *         server_name: "Slack"
 *     }
 */
export interface CreateWhiteLabelingRequest {
    /** OAuth client ID */
    client_id: string;
    /** OAuth client secret */
    client_secret: string;
    /** Optional. The name of the server */
    server_name: Klavis.OAuthServerName;
    /** Optional. OAuth callback URL */
    callback_url?: string;
    /** Optional. The UUID of the account */
    account_id?: string;
}
