/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instance_id: "instance_id"
 *     }
 */
export interface OauthAuthorizeSalesforceRequest {
    /**
     * Unique identifier for the client instance requesting authorization
     */
    instance_id: string;
    /**
     * Client ID for white labeling, if not provided will use default credentials
     */
    client_id?: string;
    /**
     * Optional OAuth scopes to request (space-separated string)
     */
    scope?: string;
    /**
     * Optional URL to redirect to after authorization completes
     */
    redirect_url?: string;
    /**
     * Salesforce instance URL (e.g., https://mycompany.salesforce.com). If not provided, will use default login.salesforce.com
     */
    instance_url?: string;
}
