/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         instance_id: "instance_id",
 *         client_id: "client_id",
 *         scope: "scope",
 *         redirect_url: "redirect_url"
 *     }
 */
export interface OauthAuthorizeCloseRequest {
    /**
     * Unique identifier for the client instance requesting authorization
     */
    instance_id: string;
    /**
     * Client ID for white labeling, if not provided will use default credentials
     */
    client_id?: string;
    /**
     * Optional OAuth scopes to request (comma-separated string)
     */
    scope?: string;
    /**
     * Optional URL to redirect to after authorization completes
     */
    redirect_url?: string;
}
