/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Klavis from "../../../index.js";

export type McpServerGetToolsResponse = Klavis.ListToolsResponse | Klavis.MultiServerToolsResponse;
