/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("CalcomOauth", () => {
    test("authorizeCalcom", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/oauth/calcom/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calcomOauth.authorizeCalcom({
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("calcomClientCredentialsAuth", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", message: "message" };
        server
            .mockEndpoint()
            .get("/oauth/calcom/client-credentials")
            .header("x-cal-client-id", "x-cal-client-id")
            .header("x-cal-secret-key", "x-cal-secret-key")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calcomOauth.calcomClientCredentialsAuth({
            "x-cal-client-id": "x-cal-client-id",
            "x-cal-secret-key": "x-cal-secret-key",
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            status: "status",
            message: "message",
        });
    });
});
