/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("CanvaOauth", () => {
    test("authorizeCanva", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/oauth/canva/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.canvaOauth.authorizeCanva({
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("canvaOAuthCallback", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", message: "message" };
        server
            .mockEndpoint()
            .get("/oauth/canva/callback")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.canvaOauth.canvaOAuthCallback();
        expect(response).toEqual({
            status: "status",
            message: "message",
        });
    });

    test("refreshCanvaToken", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", message: "message" };
        server
            .mockEndpoint()
            .post("/oauth/canva/refresh_token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.canvaOauth.refreshCanvaToken({
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            status: "status",
            message: "message",
        });
    });
});
