/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("IntercomOauth", () => {
    test("authorizeintercom_oauth", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/oauth/intercom/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.intercomOauth.authorizeintercomOauth({
            instance_id: "instance_id",
            redirect_url: "redirect_url",
            force_refresh: true,
        });
        expect(response).toEqual({
            key: "value",
        });
    });
});
