/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("JotformOauth", () => {
    test("authorizejotform_oauth", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/oauth/jotform/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jotformOauth.authorizejotformOauth({
            instance_id: "instance_id",
            redirect_url: "redirect_url",
            force_refresh: true,
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("refresh_jotform_oauth_token", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", message: "message" };
        server
            .mockEndpoint()
            .post("/oauth/jotform/refresh_token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jotformOauth.refreshJotformOauthToken({
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            status: "status",
            message: "message",
        });
    });
});
