/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("McpServer", () => {
    test("call_tools", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { serverUrl: "serverUrl", toolName: "toolName" };
        const rawResponseBody = {
            success: true,
            result: { content: [{ key: "value" }], isError: true },
            error: "error",
        };
        server
            .mockEndpoint()
            .post("/mcp-server/call-tool")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.callTools({
            serverUrl: "serverUrl",
            toolName: "toolName",
        });
        expect(response).toEqual({
            success: true,
            result: {
                content: [
                    {
                        key: "value",
                    },
                ],
                isError: true,
            },
            error: "error",
        });
    });

    test("list_tools", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { serverUrl: "serverUrl" };
        const rawResponseBody = { success: true, tools: [{ key: "value" }], format: "openai", error: "error" };
        server
            .mockEndpoint()
            .post("/mcp-server/list-tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.listTools({
            serverUrl: "serverUrl",
        });
        expect(response).toEqual({
            success: true,
            tools: [
                {
                    key: "value",
                },
            ],
            format: "openai",
            error: "error",
        });
    });

    test("createServerInstance", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { serverName: "Affinity", userId: "userId", platformName: "platformName" };
        const rawResponseBody = { serverUrl: "serverUrl", instanceId: "instanceId", oauthUrl: "oauthUrl" };
        server
            .mockEndpoint()
            .post("/mcp-server/instance/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.createServerInstance({
            serverName: "Affinity",
            userId: "userId",
            platformName: "platformName",
        });
        expect(response).toEqual({
            serverUrl: "serverUrl",
            instanceId: "instanceId",
            oauthUrl: "oauthUrl",
        });
    });

    test("createUnifiedMCPServerInstance", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { userId: "userId", platformName: "platformName" };
        const rawResponseBody = { serverUrl: "serverUrl", instanceId: "instanceId", oauthUrl: "oauthUrl" };
        server
            .mockEndpoint()
            .post("/mcp-server/unified/instance/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.createUnifiedMcpServerInstance({
            userId: "userId",
            platformName: "platformName",
        });
        expect(response).toEqual({
            serverUrl: "serverUrl",
            instanceId: "instanceId",
            oauthUrl: "oauthUrl",
        });
    });

    test("createSelfHostedServerInstance", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { serverName: "Affinity", userId: "userId" };
        const rawResponseBody = { instanceId: "instanceId", oauthUrl: "oauthUrl" };
        server
            .mockEndpoint()
            .post("/mcp-server/self-hosted/instance/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.createSelfHostedServerInstance({
            serverName: "Affinity",
            userId: "userId",
        });
        expect(response).toEqual({
            instanceId: "instanceId",
            oauthUrl: "oauthUrl",
        });
    });

    test("getServerInstance", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            instanceId: "instanceId",
            authNeeded: true,
            isAuthenticated: true,
            serverName: "serverName",
            platform: "platform",
            externalUserId: "externalUserId",
        };
        server
            .mockEndpoint()
            .get("/mcp-server/instance/get/instance_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.getServerInstance("instance_id");
        expect(response).toEqual({
            instanceId: "instanceId",
            authNeeded: true,
            isAuthenticated: true,
            serverName: "serverName",
            platform: "platform",
            externalUserId: "externalUserId",
        });
    });

    test("deleteInstanceAuth", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };
        server
            .mockEndpoint()
            .delete("/mcp-server/instance/delete-auth/instance_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.deleteInstanceAuth("instance_id");
        expect(response).toEqual({
            success: true,
            message: "message",
        });
    });

    test("deleteServerInstance", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };
        server
            .mockEndpoint()
            .delete("/mcp-server/instance/delete/instance_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.deleteServerInstance("instance_id");
        expect(response).toEqual({
            success: true,
            message: "message",
        });
    });

    test("get_tools", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { tools: [{ name: "name", description: "description" }] };
        server
            .mockEndpoint()
            .get("/mcp-server/tools/Affinity")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.getTools("Affinity");
        expect(response).toEqual({
            tools: [
                {
                    name: "name",
                    description: "description",
                },
            ],
        });
    });

    test("getAllMcpServers", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            servers: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tools: [{ name: "name", description: "description" }],
                    authNeeded: true,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/mcp-server/servers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.getAllMcpServers();
        expect(response).toEqual({
            servers: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tools: [
                        {
                            name: "name",
                            description: "description",
                        },
                    ],
                    authNeeded: true,
                },
            ],
        });
    });

    test("setInstanceAuthToken", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instanceId: "instanceId", authToken: "authToken" };
        const rawResponseBody = { success: true, message: "message" };
        server
            .mockEndpoint()
            .post("/mcp-server/instance/set-auth-token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.setInstanceAuthToken({
            instanceId: "instanceId",
            authToken: "authToken",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
        });
    });

    test("getInstanceAuthData", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, authData: { key: "value" }, error: "error" };
        server
            .mockEndpoint()
            .get("/mcp-server/instance/get-auth/instance_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.getInstanceAuthData("instance_id");
        expect(response).toEqual({
            success: true,
            authData: {
                key: "value",
            },
            error: "error",
        });
    });

    test("getOAuthUrl", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { serverName: "Affinity", instanceId: "instanceId" };
        const rawResponseBody = { oauthUrl: "oauthUrl" };
        server
            .mockEndpoint()
            .post("/mcp-server/oauth-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServer.getOAuthUrl({
            serverName: "Affinity",
            instanceId: "instanceId",
        });
        expect(response).toEqual({
            oauthUrl: "oauthUrl",
        });
    });
});
