/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("OnedriveOauth", () => {
    test("refreshToken", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", message: "message", data: { key: "value" } };
        server
            .mockEndpoint()
            .post("/oauth/onedrive/refresh_token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.onedriveOauth.refreshToken({
            instance_id: "instance_id",
        });
        expect(response).toEqual({
            status: "status",
            message: "message",
            data: {
                key: "value",
            },
        });
    });
});
