/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("Sandbox", () => {
    test("createSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            sandbox_id: "sandbox_id",
            server_url: "server_url",
            server_name: "jira",
            status: "idle",
            message: "message",
        };
        server.mockEndpoint().post("/sandbox/jira").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.sandbox.createSandbox("jira");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            server_url: "server_url",
            server_name: "jira",
            status: "idle",
            message: "message",
        });
    });

    test("getSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            sandbox_id: "sandbox_id",
            server_url: "server_url",
            server_name: "jira",
            status: "idle",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/sandbox/jira/sandbox_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandbox.getSandbox("jira", "sandbox_id");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            server_url: "server_url",
            server_name: "jira",
            status: "idle",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("deleteSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { sandbox_id: "sandbox_id", status: "idle", message: "message" };
        server
            .mockEndpoint()
            .delete("/sandbox/jira/sandbox_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandbox.deleteSandbox("jira", "sandbox_id");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            status: "idle",
            message: "message",
        });
    });

    test("resetSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { sandbox_id: "sandbox_id", status: "idle", message: "message" };
        server
            .mockEndpoint()
            .post("/sandbox/jira/sandbox_id/reset")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandbox.resetSandbox("jira", "sandbox_id");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            status: "idle",
            message: "message",
        });
    });

    test("initializeSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            sandbox_id: "sandbox_id",
            status: "idle",
            message: "message",
            records_created: { key: 1 },
        };
        server
            .mockEndpoint()
            .post("/sandbox/snowflake/sandbox_id/initialize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandbox.initializeSandbox("sandbox_id");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            status: "idle",
            message: "message",
            records_created: {
                key: 1,
            },
        });
    });

    test("dumpSandbox", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            sandbox_id: "sandbox_id",
            server_name: "jira",
            dumped_at: "2024-01-15T09:30:00Z",
            data: { key: "value" },
        };
        server
            .mockEndpoint()
            .get("/sandbox/snowflake/sandbox_id/dump")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sandbox.dumpSandbox("sandbox_id");
        expect(response).toEqual({
            sandbox_id: "sandbox_id",
            server_name: "jira",
            dumped_at: "2024-01-15T09:30:00Z",
            data: {
                key: "value",
            },
        });
    });
});
