/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { KlavisClient } from "../../src/Client";

describe("ZoomOauth", () => {
    test("authorizeZoom", async () => {
        const server = mockServerPool.createServer();
        const client = new KlavisClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/oauth/zoom/authorize")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.zoomOauth.authorizeZoom({
            instance_id: "instance_id",
            client_id: "client_id",
            scope: "scope",
            redirect_url: "redirect_url",
        });
        expect(response).toEqual({
            key: "value",
        });
    });
});
