/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { McpServer } from "./api/resources/mcpServer/client/Client.js";
import { WhiteLabeling } from "./api/resources/whiteLabeling/client/Client.js";
import { User } from "./api/resources/user/client/Client.js";
import { Oauth } from "./api/resources/oauth/client/Client.js";

export declare namespace KlavisClient {
    export interface Options {
        environment?: core.Supplier<environments.KlavisEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class KlavisClient {
    protected readonly _options: KlavisClient.Options;
    protected _mcpServer: McpServer | undefined;
    protected _whiteLabeling: WhiteLabeling | undefined;
    protected _user: User | undefined;
    protected _oauth: Oauth | undefined;

    constructor(_options: KlavisClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "klavis",
                    "X-Fern-SDK-Version": "2.5.0",
                    "User-Agent": "klavis/2.5.0",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get mcpServer(): McpServer {
        return (this._mcpServer ??= new McpServer(this._options));
    }

    public get whiteLabeling(): WhiteLabeling {
        return (this._whiteLabeling ??= new WhiteLabeling(this._options));
    }

    public get user(): User {
        return (this._user ??= new User(this._options));
    }

    public get oauth(): Oauth {
        return (this._oauth ??= new Oauth(this._options));
    }
}
