/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Klavis from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace CanvaOauth {
    export interface Options {
        environment?: core.Supplier<environments.KlavisEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class CanvaOauth {
    protected readonly _options: CanvaOauth.Options;

    constructor(_options: CanvaOauth.Options = {}) {
        this._options = _options;
    }

    /**
     * Start Canva OAuth flow with PKCE
     *
     * Parameters:
     * - instance_id: Identifier for the instance requesting authorization
     * - client_id: Optional client ID for white labeling
     * - scope: Optional scopes to request (space-separated, e.g., "design:meta:read profile:read")
     * - redirect_url: Optional URL to redirect to after authorization completes
     *
     * @param {Klavis.AuthorizeCanvaRequest} request
     * @param {CanvaOauth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.canvaOauth.authorizeCanva({
     *         instance_id: "instance_id"
     *     })
     */
    public authorizeCanva(
        request: Klavis.AuthorizeCanvaRequest,
        requestOptions?: CanvaOauth.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__authorizeCanva(request, requestOptions));
    }

    private async __authorizeCanva(
        request: Klavis.AuthorizeCanvaRequest,
        requestOptions?: CanvaOauth.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { instance_id: instanceId, client_id: clientId, scope, redirect_url: redirectUrl } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["instance_id"] = instanceId;
        if (clientId != null) {
            _queryParams["client_id"] = clientId;
        }

        if (scope != null) {
            _queryParams["scope"] = scope;
        }

        if (redirectUrl != null) {
            _queryParams["redirect_url"] = redirectUrl;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                "oauth/canva/authorize",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError("Timeout exceeded when calling GET /oauth/canva/authorize.");
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Handle Canva OAuth callback
     *
     * This endpoint is called by Canva after the user authorizes the application.
     * It exchanges the authorization code for an access token using PKCE.
     *
     * @param {Klavis.CanvaOAuthCallbackRequest} request
     * @param {CanvaOauth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.BadRequestError}
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.canvaOauth.canvaOAuthCallback()
     */
    public canvaOAuthCallback(
        request: Klavis.CanvaOAuthCallbackRequest = {},
        requestOptions?: CanvaOauth.RequestOptions,
    ): core.HttpResponsePromise<Klavis.CanvaOAuthSuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__canvaOAuthCallback(request, requestOptions));
    }

    private async __canvaOAuthCallback(
        request: Klavis.CanvaOAuthCallbackRequest = {},
        requestOptions?: CanvaOauth.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.CanvaOAuthSuccessResponse>> {
        const { code, state, error, error_description: errorDescription } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (code != null) {
            _queryParams["code"] = code;
        }

        if (state != null) {
            _queryParams["state"] = state;
        }

        if (error != null) {
            _queryParams["error"] = error;
        }

        if (errorDescription != null) {
            _queryParams["error_description"] = errorDescription;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                "oauth/canva/callback",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.CanvaOAuthSuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Klavis.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError("Timeout exceeded when calling GET /oauth/canva/callback.");
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Refresh an expired Canva access token using the stored refresh token
     *
     * Parameters:
     * - instance_id: Identifier for the instance requesting token refresh
     *
     * Returns:
     * - Success response if token was refreshed successfully, error response otherwise
     *
     * @param {Klavis.RefreshCanvaTokenOauthCanvaRefreshTokenPostRequest} request
     * @param {CanvaOauth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Klavis.BadRequestError}
     * @throws {@link Klavis.UnprocessableEntityError}
     *
     * @example
     *     await client.canvaOauth.refreshCanvaToken({
     *         instance_id: "instance_id"
     *     })
     */
    public refreshCanvaToken(
        request: Klavis.RefreshCanvaTokenOauthCanvaRefreshTokenPostRequest,
        requestOptions?: CanvaOauth.RequestOptions,
    ): core.HttpResponsePromise<Klavis.CanvaOAuthSuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__refreshCanvaToken(request, requestOptions));
    }

    private async __refreshCanvaToken(
        request: Klavis.RefreshCanvaTokenOauthCanvaRefreshTokenPostRequest,
        requestOptions?: CanvaOauth.RequestOptions,
    ): Promise<core.WithRawResponse<Klavis.CanvaOAuthSuccessResponse>> {
        const { instance_id: instanceId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["instance_id"] = instanceId;
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.KlavisEnvironment.Default,
                "oauth/canva/refresh_token",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Klavis.CanvaOAuthSuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Klavis.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Klavis.UnprocessableEntityError(
                        _response.error.body as Klavis.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.KlavisError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.KlavisError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.KlavisTimeoutError("Timeout exceeded when calling POST /oauth/canva/refresh_token.");
            case "unknown":
                throw new errors.KlavisError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.apiKey);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
