/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GmailOAuthCallbackRequest {
    /**
     * Authorization code returned by Gmail
     */
    code?: string;
    /**
     * State parameter containing encoded authorization data
     */
    state?: string;
    /**
     * Error code returned by Gmail, if any
     */
    error?: string;
    /**
     * Detailed error description from Gmail, if any
     */
    error_description?: string;
}
